<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.zhsqjm</groupId>
        <artifactId>tl-mqtt</artifactId>
        <version>1.2.0</version>
    </parent>
    <artifactId>tlmqtt-rule</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>tlmqtt-rule-sink</module>
        <module>tlmqtt-rule-source</module>
        <module>tlmqtt-rule-engine</module>
    </modules>
    <version>1.2.0</version>
    <name>tlmqtt-rule</name>



    <dependencies>

        <dependency>
            <groupId>io.github.zhsqjm</groupId>
            <artifactId>tlmqtt-common</artifactId>
            <version>1.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.googlecode.aviator</groupId>
            <artifactId>aviator</artifactId>
            <version>5.3.3</version>
        </dependency>

    </dependencies>
</project>
