<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.zhsqjm</groupId>
        <artifactId>tlmqtt-authentication</artifactId>
        <version>1.2.0</version>
    </parent>
    <artifactId>tlmqtt-authentication-sql</artifactId>
    <name>tlmqtt-authentication-sql</name>
    <url>http://maven.apache.org</url>

    <dependencies>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>

    </dependencies>
</project>
