spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        enabled: true          # 启用连接池
        max-active: 64        # 最大活跃连接数
        max-idle: 32           # 最大空闲连接
        min-idle: 16          # 最小空闲连接
        max-wait: 50ms      # 最大等待时间（获取连接超时时间）
        time-between-eviction-runs: 30s # 空闲连接检测间隔
server:
  port: 8001
logging:
  level:
    com.tlmqtt.core.handler: debug
    com.tlmqtt.core.message: debug
    com.tlmqtt.boot.store: info
    com.tlmqtt.core.retry: debug
    com.tlmqtt.core.manager: debug
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      redis: true